name: Docker Image Build and Push

on:
  workflow_call:
    # inputs:
    #   workflow_id:
    #     - "Build"
    #   action_id:
    #     - "imagepush"

jobs:
    image_push:
        runs-on: java_build
        env:
            DOCKER_IMAGE: pezebuike/petapp:${{ github.sha }}

        steps:
            - name: Build Docker Image
              run: |
                sudo docker build -t ${{ env.DOCKER_IMAGE }} .
                sudo docker push ${{ env.DOCKER_IMAGE }} > docker_image.tar

            - name: Upload Docker Image Artifact
              uses: actions/upload-artifact@v2
              with:
                name: docker-image
                path: docker_image.tar

            - name: Log into GitHub Container Registry
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: pull docker image
              run: docker pull ${{ env.DOCKER_IMAGE }}
                