name: Docker Image Build and Push

on:
  workflow_call:
    # inputs:
    #   workflow_id:
    #     - "Build"
    #   action_id:
    #     - "imagepush"

jobs:
    image_push:
        runs-on: java_build
        env:
            USER: pezebuike # docker registry user name 
            DOCKER_IMAGE: petapp:${{ github.sha }} # This will be combined with the container registry user name to generate a tag for the image
            # TAG: pezebuike/petapp:${{github.sha}} 
            REGISTRY: ghcr.io
        steps:
            - name: Build Docker Image
              run: |
                sudo docker build -t ${{ env.USER }}/${{ env.DOCKER_IMAGE }} .
                sudo docker push ${{ env.DOCKER_IMAGE }} > docker_image.tar

            - name: Upload Docker Image Artifact
              uses: actions/upload-artifact@v2
              with:
                name: docker-image
                path: docker_image.tar

            - name: Log into GitHub Container Registry
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{env.REGISTRY}} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: pull docker image
              run: docker pull ${{ env.DOCKER_IMAGE }}
                