name: Build

on:
  workflow_call:

permissions: 
  id-token: write
  contents: read

jobs:
  build-and-upload:
    runs-on: java_build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: target/*.jar

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          oidc-provider-name: github-jfrog
          oidc-audience: my-aud
        env:
          JAVA_HOME: /home/ubuntu/actions-runner/_work/_tool/Java_Adopt_jdk/17.0.13-11/x64
          JAVA_HOME_17_X64: /home/ubuntu/actions-runner/_work/_tool/Java_Adopt_jdk/17.0.13-11/x64

      - name: Configure JFrog CLI
        env:
          CI: true # Suppress interactive prompts
          JF_URL: ${{ secrets.JFROG_URL }}
          JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
        run: |
          jf c add --url=${{ secrets.JFROG_URL }} --access-token=${{ secrets.JFROG_TOKEN }} --interactive=false

      - name: Upload JAR to JFrog
        env:
          CI: true # Suppress interactive prompts
        run: |
          jf rt u "target/*.jar" "petjfrog-repo/"

# name: Build

# on:
#   workflow_call:
#      # inputs:
#      #   workflow_id:
#      #     - "Build"
#      #   action_id:
#      #     - "javabuild"

# permissions: 
#   id-token: write
   

# jobs:
#   build-and-upload:
#     runs-on: java_build
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Set up JDK 17
#         uses: actions/setup-java@v4
#         with:
#           distribution: 'adopt'
#           java-version: '17'
#           cache: 'maven'

#       - name: Cache Maven Dependencies
#         uses: actions/cache@v4
#         with:
#           path: ~/.m2/repository
#           key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

#       - name: Build with Maven
#         run: mvn clean install -DskipTests=true

#       - name: Upload Build Artifact
#         uses: actions/upload-artifact@v3
#         with:
#           name: jar
#           path: target/*.jar

#       - name: Setup JFrog CLI
#         uses: jfrog/setup-jfrog-cli@v4
#         env:
#           JFROG_url: ${{ secrets.JFROG_URL }}        
#         with:
#           oidc-provider-name: github-jfrog
#           oidc-audience: my-aud

      
#       # - name: Configure JFrog CLI
#       #   env:
#       #     CI: true # Suppress interactive prompts
#       #     JFROG_URL: ${{ secrets.JFROG_URL }}
#       #     JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
#       #   run: |
#       #     jf c add --url=${{secrets.JFROG_URL}} --access-token=${{secrets.JFROG_TOKEN}} --interactive=false
         

#       - name: Upload JAR to JFrog
#         env:
#           CI: true # Suppress interactive prompts
#         run: |
#           jf rt u "target/*.jar" "petjfrog-repo/"
            