name: Build

on:
  workflow_call:
    # inputs:
    #   workflow_id:
    #     - "Build"
    #   action_id:
    #     - "javabuild"

jobs:
  build:
    runs-on: java_build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'

      - name: Catch Maven Dependencies
        uses: actions/cache@v4
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
         name: jar
         path: target/*.jar

      # - name: Configure jfrog CLI
      #   env:
      #     JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
      #   run: |
      #     jfrog config add jfrog --artifactory-url=https://trial1u1cj3.jfrog.io --user=ezebuikemichael@gmail.com --opikey=${{ secrets.JFROG_API_KEY }} --interactive=false

      - name: Setup JFROG CLI
        uses: jfrog/setup-jfrog-cli@v3        
        with:
            version: latest
      
      - name: Configure JFrog CLI
        env:
            JF_URL: ${{ secrets.JFROG_URL }}
            JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }}
        run: |
            jf c add --url=$JF_URL --access-token=$JF_ACCESS_TOKEN --interactive=false
        
            

      - name: Upload JAR to JFrog
        run: |
            sudo jf rt u "target/*.jar" "petjfrog-repo/"
           
            