name: Build

on:
  workflow_call:
    # inputs:
    #   workflow_id:
    #     - "Build"
    #   action_id:
    #     - "javabuild"

jobs:
  build-and-upload:
    runs-on: java_build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: target/*.jar

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3        
        with:
          version: latest
      
      - name: Configure JFrog CLI
        env:
          CI: true # Suppress interactive prompts
          JFROG_URL: ${{ secrets.JFROG_URL }}
          JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
        run: |
          jf c add --url=${{secrets.JFROG_URL}} --access-token=${{secrets.JFROG_TOKEN}} --interactive=false
          jf c use default

      - name: Upload JAR to JFrog
        env:
          CI: true # Suppress interactive prompts
        run: |
          jf rt u "target/*.jar" "petjfrog-repo/"
            