name: CI Pipline

on:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - main

env:
        DOCKER_IMAGE: ezy1016/petapp:${{ github.sha }}
        MAVEN_CLI_OPTS: "DskipTests=true -B -V"

jobs:
  Build:
    uses: ./.github/workflows/javabuild.yml
    secrets: inherit  

  sonar:
    uses: ./.github/workflows/sonar.yml 
    needs: Build
    secrets: inherit
    
  test:
    uses: ./.github/workflows/test.yml
    needs: sonar
    secrets: inherit

  imagepush:
    uses: ./.github/workflows/imagepush.yml
    needs: test
    secrets: inherit

  # deploy:
  #   uses: ./.github/workflows/deploy.yml
  #   needs: imagepush
  #   secrets: inherit



  
        