name: Sonar Scan

on:
    workflow_call:
        # inputs:
        # workflow_id:
        #     - "Build"
        # action_id:
        #     - "sonar"

jobs:
    sonar:
        runs-on: java-build
        # needs: Build # Ensure Sonar runs after Build
        steps:
            - name: SonarCloud Scan
              run: |
                mvn sonar:sonar 
                -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} 
                -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
                -Dsonar.host.url=${{ secrets.SONAR_URL }}
                -Dsonar.login=${{ secrets.SONAR_TOKEN }}