name: Trivy scan 

on:
  workflow_call:

jobs:
    trivy:
      runs-on: java_build 
      env:
        USER: pezebuike # docker registry user name 
        DOCKER_IMAGE: petapp:${{ github.sha }} # This will be combined with the container registry user name to generate a tag for the image
        # TAG: pezebuike/petapp:${{github.sha}} 
        REGISTRY: ghcr.io
      steps:
        - name: Run Trivy vulnerability scanner 
          uses: aquasecurity/trivy-action@0.28.0
          with:
            image-ref: '${{ env.USER }}/${{ env.DOCKER_IMAGE }}'
            scanners: 'vuln,secret,config'
            format: 'sarif'
            output: 'trivy-image-results.sarif'
            exit-code: '1'
              
            # exit_code-$?
            # echo "Exit Code : $exit_code"

            # if [["${exit_code}" == 1 ]]; then
            #     echo"image scanning faild. Vulnerability found"
            #     exit-1;
            # else
            #     echo "Image scanning passed. No CRITICAL Vulnerability found"
            # fi;
        
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'

        - name: upload the scan result to github security
          uses: github/codeql-action/upload-sarif@v2
          with:
            sarif_file: 'trivy-image-results.sarif'
            category: 'image'

            # exit_code-$?
            # echo "Exit Code : $exit_code"

            # if [["${exit_code}" == 1 ]]; then
            #     echo"image scanning faild. Vulnerability found"
            #     exit-1;
            # else
            #     echo "Image scanning passed. No CRITICAL Vulnerability found"
            # fi;
        
    

